### ISSUE TITLE
Locating the fbc.exe file

### ISSUE THREAD

**Issue by Astronaronic** [XusinboyBekchanov/VisualFBEditor#3]
How would I get VFBE to know where the FBC file is?
In others like FBIde, there's an option for it. How would I do it in VFBE?

**Comment by XusinboyBekchanov** [comment]
fbc.exe can be obtained here:
https://www.freebasic.net/forum/viewforum.php?f=1&sid=2508c14fea7ae15747122afb77b30fa4

**Comment by Astronaronic** [comment]
I've got it, it's just that VisualFBEditor can't find it. How would I get it to know where the location of the file is?

**Comment by XusinboyBekchanov** [comment]
When installing freebasic you yourself specify where to install it. The freebasic installer itself defaults to "C:\Program Files\FreeBasic\fbc.exe". On VisualFBEditor you need to specify this path as follows: Menu Service -> Options (the Settings dialog opens), then in the Compiler point, specify the path.

**Comment by Astronaronic** [comment]
Ah yes, it works! Thanks a bunch.

**Comment by JanuszChmiel** [comment]
I Am heavily fighting with Options GUI. Arrow keys do not work with screen reader. Many object elements are not focusable by pressing TAB or SHIFT+TAB. Please, could you send VisualFBEditor32.ini file prepared so I could use Visual editor with 
C:\FreeBasic\FreeBASIC-1.07.1-win32
path?
I know, that visuality can not math with full accessibility and if all GUI object would be focusable by pressing arrow keys and by pressing TAB or SHIFT+TAB it would make yours GUi ugly. SO I Am pleasing you with deepest respect.
send me
0The prepared ini file as a attachment to this Github issue so I could finally experiment with yours sample code.

**Comment by XusinboyBekchanov** [comment]
In the new version I also work on TAB.

Here is the ini file
[VisualFBEditor32.ini.zip](https://github.com/XusinboyBekchanov/VisualFBEditor/files/4564937/VisualFBEditor32.ini.zip)

**Comment by JanuszChmiel** [comment]
Thank you very much for yours kind access to my plea. I have one question.
Which algorithm did you used to incorporated yours .dll to compiled
executable? I mean framework.dll which creates GUI. Is it possible to also
incorporate other dlls to .exe if The author allow it? It is very
interesting approach.

**Comment by JanuszChmiel** [comment]
Oh thank you very much. Finally, I can compile!!! I have done my best to
understand The structure of .ini file, but I had no success.
Please, tell me, from which main object is inherited yours editable field
which is used inside yours IDe to display source code and line numbers.
Line numbers and source code text can be read by using NVDA screen reader
build in GDI hooks special complex C dode to get text from GDI32. But arrow
keys produces only empty line message.
Yours object Class name is
EditControl
I AM guessing that you had to developed this object from scratch and that
The complex code resides inside source code of myframework library. That you
do not simply call Windows API.

**Comment by JanuszChmiel** [comment]
Oh, You have yours source code very well structured. I AM analysing .bas
source for yours Editcontrol object. You are very thalented programmer.

**Comment by XusinboyBekchanov** [comment]
The compiled dll file is called mff.dll on Windows, libmff.so on Linux.
By default, included library files through #include are included in exe (i.e. no dll is needed). But you can also dynamically load the library as in the Addin example. Not all functions have been exported yet.

In my opinion, without tricks it is not possible to include other dlls in exe. MyFbFramework is included in exe because it is the source code. Other dlls can be connected dynamically.

**Comment by JanuszChmiel** [comment]
Ok. Do not be afraid, I will stop intruding you. Thank you very much that
you are so friendly. Many developers do not like visually impaired advanced
users or programmers, who would want to create apps by using ttheir GUIS.
And yours library finally brought my desired dream to reality. I will be
finally able to develop without Autoid, Autohodkey, FNX Basic and without
similar pseudo compilers. It is good, that include includes source code of
yours library. I will had to sutdy hard many functions and subs to create
GUI efficiently.
I will try to make Excel table with functions and subs for fast searching
instead of arrowing inside The source code. It will be some work, but I will
give it A try.

**Comment by XusinboyBekchanov** [comment]
EditControl inherited from Control (from MyFbFramework). But I don’t know NVDA screen reader.
I did not understand the problem with the arrows. To go to functions and procedures, there is a combo box at the top of EditControl.

**Comment by JanuszChmiel** [comment]
When Focus is placed inside editable field NVDA and also other screen
readers can only say empty line. Only if special GDI hooks is being used by
pressing numeric numbers 7 and 9 to navigating between lines, it is possible
to work with The ditable field.
NVDA correctly recognizes that it is Editable field. But it can not directly
read its content when up, down, left or right arrow keys are being used.

**Comment by XusinboyBekchanov** [comment]
Sources are open. You yourself can try to correct this situation. If correcting, let me know, we will add improvements to this Control.

**Comment by rexxitall** [comment]
can be closed. IDE has setup for the compiler paths

**Comment by XusinboyBekchanov** [comment]
You say it right.
